#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/justas/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/justas/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/justas/Repositories/OlfactoryBulb/prev-ob-models/BhallaBower1993-HOC/x86_64/.libs/libnrnmech.so" "$@"
